sudo: required

services:
  - docker

before_install:
  - docker pull robertoaloi/docker-thebeambook:latest

script:
  - docker run -v $TRAVIS_BUILD_DIR:/book --name thebeambook robertoaloi/docker-thebeambook make

after_error:
  - docker logs thebeambook

after_failure:
  - docker logs thebeambook

deploy:
  provider: releases
  api_key:
    secure: [secure-key-goes-here]
  file: beam-book.pdf
  skip_cleanup: true
  on:
    repo: happi/theBeamBook
    tags: true
